---
openapi: 3.0.0
info:
  title: Notes
  description: Exemplo de api para registro de notas
  contact:
    name: Anderson Santos
    url: http://localhost/contracts
    email: anderson@sysmap.com.br
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
paths:
  /notes:
    get:
      summary: Recupera todas as notas
      responses:
        200:
          description: Retorna todos as notas encontradas.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
              examples:
                Found:
                  summary: Return a list
                  value: |-
                    [
                    {
                        "_id": "abc123",
                        "title": "This is a note.",
                        "description": "This is the note content."
                    },
                    {
                        "_id": "abc123",
                        "title": "This is a note.",
                        "description": "This is the note content."
                    }
                    ]
                Not Found:
                  summary: Return a empty list
                  value: '[]'
        401:
          description: Problema com o token. Você tem acesso a este recurso?
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationError'
        403:
          description: Não tem autorização para acessar notas.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorizationError'
      security:
      - apikey: []
    post:
      summary: Cria uma nota
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
            examples:
              Cria uma nota com o id atribuído:
                value:
                  id: abc123
                  title: This is a note.
                  description: This is the note content.
              Cria uma nota e deixa a api atribuir um id:
                value:
                  title: This is a note.
                  description: This is the note content.
        required: true
      responses:
        200:
          description: Nota criada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
              examples:
                Nota criada:
                  value:
                    _id: abc123
                    title: This is a note.
                    description: This is the note content.
        400:
          description: Alguma coisa está errada com o corpo do seu request. Você passou
            todos os parametros obrigatórios?
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
              examples:
                Validação do valor do parâmetro:
                  summary: Valor do atributo
                  value:
                    message: 800
                    type: Title is too long. The Title field should not exceed 60
                      characters.
                    code: ValidatioException
                Validação da obrigatoriedade do parametro:
                  summary: Falta de atributo
                  value:
                    message: 810
                    type: O título é obrigatório. Você deve informa-lo na sua requisição
                    code: ValidatioException
                Id existente:
                  summary: Tentativa de criar uma nota com um id que existe. Para
                    atualizar utilize o método PUT.
                  value:
                    message: 820
                    type: ID já existe. Caso queira criar com um id diferente, remova-o
                      da requisição.
                    code: ValidatioException
        401:
          description: Problema com o token. Você tem acesso a este recurso?
          content:
            application/json:
              examples:
                Problema com o token:
                  value:
                    message: 600
                    type: Problema de autorização neste servidor, verifique a validade
                      do token.
                    code: AuthenticationException
        403:
          description: Não tem autorização para criar notas.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorizationError'
              examples:
                Sem perfil para acessar este recurso:
                  value:
                    message: 300
                    type: Você não tem permissão para acessar este recurso.
                    code: AuthorizationException
      security:
      - apikey: []
    servers:
    - url: http://localhost:5000
      description: Test e development
  /notes/{id}:
    get:
      summary: Retorna uma nota
      responses:
        200:
          description: Retorna uma nota
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
              examples:
                Registro encontrado:
                  value:
                    _id: abc123
                    title: This is a note.
                    description: This is the note content.
        401:
          description: Problema com o token. Você tem acesso a esta nota?
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationError'
        403:
          description: Não tem permissão para acessar esta nota.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorizationError'
        404:
          description: Nota não encontrado.
      security:
      - apikey: []
    put:
      summary: Atualiza uma nota
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
            examples:
              Atualiza todos os atributos:
                value:
                  title: This is a note.
                  description: This is the note content.
        required: true
      responses:
        200:
          description: Nota atualizada.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
        400:
          description: Alguma coisa está errada com o corpo do seu request. Você passou
            todos os parametros obrigatórios?
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
              examples:
                Validação do valor do parâmetro:
                  summary: Valor do atributo
                  value:
                    message: 800
                    type: Title is too long. The Title field should not exceed 60
                      characters.
                    code: ValidatioException
                Validação da obrigatoriedade do parametro:
                  summary: Falta de atributo
                  value:
                    message: 810
                    type: O título é obrigatório. Você deve informa-lo na sua requisição
                    code: ValidatioException
                ID informado.:
                  summary: ID não pode ser atualizado
                  value:
                    message: 820
                    type: O id não pode ser atualizado, remova-o da requisição.
                    code: ValidatioException
        401:
          description: Problema com o token. Você tem acessar esta API?
          content:
            application/json:
              examples:
                Problema com o token:
                  value:
                    message: 600
                    type: Problema de autorização neste servidor, verifique a validade
                      do token.
                    code: AuthenticationException
        403:
          description: Não tem permissão para atualizar esta nota.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorizationError'
              examples:
                Sem perfil para acessar este recurso:
                  value:
                    message: 300
                    type: Você não tem permissão para acessar este recurso.
                    code: AuthorizationException
        404:
          description: Nota não encontrado.
      security:
      - apikey: []
    delete:
      summary: Apaga uma nota
      operationId: id
      responses:
        204:
          description: Nota apagada.
        401:
          description: Problema com o token. Você tem acessar esta API?
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationError'
        403:
          description: Não tem permissão para apagar esta nota.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorizationError'
        404:
          description: Nota não encontrado.
      security:
      - apikey: []
    servers:
    - url: http://localhost:5000
      description: Desenvolvimento e mock
    parameters:
    - name: id
      in: path
      description: Identificador de uma nota
      required: true
components:
  schemas:
    Note:
      required:
      - title
      - description
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
    AuthorizationError:
      title: Root Type for AuthorizationError
      description: The root of the AuthorizationError type's schema.
      required:
      - code
      - type
      type: object
      properties:
        message:
          type: string
        type:
          type: string
        code:
          type: number
    AuthenticationError:
      title: Root Type for AuthenticationError
      description: The root of the AuthenticationError type's schema.
      type: object
      properties:
        message:
          type: string
        type:
          type: string
        code:
          type: number
    ValidationError:
      title: Root Type for ValidationError
      description: The root of the ValidationError type's schema.
      type: object
      properties:
        message:
          type: string
        type:
          type: string
        code:
          type: number
  securitySchemes:
    apikey:
      type: apiKey
      name: apikey
      in: header
security:
- apikey: []
